### ISSUE TITLE
Support for Arrays

### ISSUE THREAD

**Issue by rishiosaur** [rishiosaur/sepia#3]

**Comment by ChristoPy** [comment]
Could Arrays support accessing indexes like in Python?
So the language itself has no need to provide functions like ```slice``` or ```splice``` which work almost the same and always confuses programmers. It can be much more easier to understand the code as well

**Comment by rishiosaur** [comment]
@ChristoPy I was actually thinking through that for a while—it feels like the optimal route to take for this. Do you have any preferred syntax? I like Rust's range operator, but implementing it'd be quite a pain.

**Comment by ChristoPy** [comment]
@rishiosaur , I think that the most easy path is doing like python does:
```python
array = ['a', 'b', 'c']

aAndB = array[0:1]
```
I don't know if its clear, but the first number inside the brackets is where the range starts and the second where it ends.
I think its more easy to parse, because you can start supporting accessing indexes initially. And after that the lexer can check for a ```:``` and an integer.

**Comment by rishiosaur** [comment]
I quite like that—I just need to finish implementing some lexical context stuff and then I'll get on implementing Arrays and Objects 😄
